[Format]
    utc_time="%a %B %d, %Y, %H:%M:%S UTC"
    msg_time="%Y-%m-%d %H:%M:%S"

[SQLite]
    file_path="snake.db"

[General]
    owners=[163521874872107009]
    default_prefix="snake "
    extra_prefixes=["~"]
    client_id="181584771510566922"