[Format]
  utc_time="%a %B %d, %Y, %H:%M:%S UTC"
  msg_time="%Y-%m-%d %H:%M:%S"

[General]
  owners=[163521874872107009]

  # Snake
  default_prefix="snake "

  # Snake
  client_id="181584771510566922"